version: '2.1'

networks:
  grav.net:
    driver: bridge

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./grav:/grav
      - ./site.conf:/etc/nginx/conf.d/site.conf
    healthcheck:
      test: ["CMD-SHELL", "nginx -t"]
      interval: 1m
      timeout: 1s
      retries: 1
    networks:
      - grav.net
  php:
    image: indigo/grav-php:latest
    volumes:
      - ./grav:/grav
    healthcheck:
      test: ["CMD-SHELL", "cgi-fcgi -bind -connect 127.0.0.1:9000"]
      interval: 1m
      timeout: 1s
      retries: 1
    networks:
      - grav.net
